# Generated by Django 6.0.7 on 2026-07-25 18:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0003_immobileimage_registerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='address',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='is_locate',
            field=models.BooleanField(default=False, verbose_name='Está Locado?'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='type_item',
            field=models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA')], max_length=100, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AlterField(
            model_name='immobileimage',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='registerlocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacao.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='registerlocation',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='registerlocation',
            name='dt_start',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='registerlocation',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='locacao.immobile', verbose_name='Imóvel'),
        ),
    ]
