# Generated by Django 6.0.7 on 2026-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0008_immobileimage_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlocation',
            name='dt_end',
            field=models.DateField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='registerlocation',
            name='dt_start',
            field=models.DateField(verbose_name='Início'),
        ),
    ]
