# Generated by Django 6.0.7 on 2026-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_auto_20260726_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobile',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código'),
        ),
    ]
