# Generated by Django 6.0.7 on 2026-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0006_alter_immobile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlocation',
            name='dt_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
    ]
