# Generated by Django 6.0.7 on 2026-07-26 16:37

import django.core.validators
import locacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0007_registerlocation_dt_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobileimage',
            name='image',
            field=models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), locacao.models.validate_image_size], verbose_name='Imagens'),
        ),
    ]
